security:
    oauth2:
      client:
        accessTokenUri: https://${client.userpool}.auth.eu-west-1.amazoncognito.com/oauth2/token
        userAuthorizationUri: https://${client.userpool}.auth.eu-west-1.amazoncognito.com/oauth2/authorize
        scope:
          - openid
          - profile
          - email
      resource:
        userInfoUri: https://${client.userpool}.auth.eu-west-1.amazoncognito.com/oauth2/userInfo

client:
  realm: GeoWeb
  name: Cognito
  frontendURL: http://localhost:3000/
  logoutUri: https://${client.userpool}.auth.eu-west-1.amazoncognito.com/logout


# https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_COXM0r1sc/.well-known/openid-configuration